### ISSUE TITLE
Textures for iron flask and bladder are lame

### ISSUE THREAD

**Issue by Gaelmare** [Gaelmare/WaterFlasks#2]
Replacements need fluid level overlay versions as well.

**Comment by Coach-mdl** [comment]
I'll give it a shot. I'm new to GitHub and I haven't done fluid overlays before so this will be an interesting experience.

**Comment by Gaelmare** [comment]
Thanks!

The current textures don't do fluid overlays. The damage bar takes on the
color of the fluid programmatically, and the fluid level is hardcoded to a
white bar right in the texture.

There would be a code change required to allow a fluid overlay, I think. At
least a blockstate instead of the model json. I just PR'd blue/red steel
buckets with overlays, and still don't understand the forge fluid overlay
magic. There could be some overlay magic with each of the fluid bar
textures that would be pretty slick.

I'll appreciate new textures, whatever you come up with!

**Comment by Coach-mdl** [comment]
![iron-water-flask](https://user-images.githubusercontent.com/59576000/71848332-1fe5cb00-30c7-11ea-9016-9bb2be4dcbba.png)
![leather-water-flask](https://user-images.githubusercontent.com/59576000/71848333-1fe5cb00-30c7-11ea-847f-e84951a3d575.png)

Here are the textures on their own. I don't quite understand the whole fluid overlay thing as I don't often do code. Maybe it's simpler and I'm overlooking it. These textures should fit in better with TFC.

**Comment by Gaelmare** [comment]
These are great! If you look at github, in
src/main/resources/assets/waterflasks/textures you'll see what you'll be
replacing.

I can add the fluid level bars myself, unless you're interested? Not sure
how to get an overlay to work with the bar.

**Comment by Coach-mdl** [comment]
No worries. Glad I could help. I left a small white area in the centre so you can make the fluid render inside. I look forward to seeing the new textures implemented!

**Comment by Gaelmare** [comment]
Would you be interested in contributing a texture for the bladder as well? What do you think of the iron flask recipe? Would a tuyere welded to a sheet as the unfinished iron flask, then adding the burlap, string and bladder make sense as an improved iron flask creation process? I would need to buff the capacity of the flask if I made it that expensive.

**Comment by Coach-mdl** [comment]
I can give it a go, I imagine a bladder wouldn't be that difficult because it's just a circle with some veins. As for the recipe, I'd keep the recipe reasonable. Have a bladder for the leather water flask. Maybe make a "Wrought iron canister" item that could be crafted from a wrought iron sheet for the metal flask. Or just use a sheet on it's own. I'm not entirely sure where the burlap would go in an iron canister, but string makes sense for both the leather and iron flask. I'll happily make a texture for the canister too!

**Comment by Gaelmare** [comment]
Both flasks are repairable with a bladder, and currently have a bladder as
part of the recipe.

I envision the burlap as part of the padding/insulation around the bladder
inside the container.

An unfinished canister texture would be great. I'll add a anvil recipe for
it. That will be fun. I tried a modpack with anvil recipes for every
tinkers item and it overflowed the anvil GUI. I can hope that bug will get
fixed.

**Comment by Coach-mdl** [comment]
![wrought-iron-canister](https://user-images.githubusercontent.com/59576000/72002819-0c11a480-3240-11ea-8b91-c8a19f82bca8.png)
![bladder (veiny)](https://user-images.githubusercontent.com/59576000/72002820-0c11a480-3240-11ea-8897-b227a6115625.png)
![bladder](https://user-images.githubusercontent.com/59576000/72002821-0c11a480-3240-11ea-8f62-ebc3778b591b.png)
@Gaelmare Here are the textures for the bladder and the canister. I see what you mean with the burlap now. These textures should work nicely. You also have a choice of what bladder you want.

**Comment by Gaelmare** [comment]
Thanks for these. I'll need a response agreeing to release these under GPLv3, same as the mod. See https://github.com/Gaelmare/WaterFlasks/blob/master/LICENSE for more information.

**Comment by Coach-mdl** [comment]
@Gaelmare Yes, I agree.

**Comment by Gaelmare** [comment]
Definitely liking these textures. On the leather flask, I have a crazy idea
that the size of the item will change based on how much water is in it.
Could you try that? I'm thinking your current texture would be about 3/4
empty.

**Comment by Coach-mdl** [comment]
I’ll see what I can come up with. After this, it might be worth releasing the update and then doing any other experimental things after. ;)

**Comment by Coach-mdl** [comment]
@Gaelmare may I ask if there’s any other platforms you’d prefer me to message you on?

**Comment by Coach-mdl** [comment]
![iron-water-flask (broken)](https://user-images.githubusercontent.com/59576000/72207503-cb10ce80-3491-11ea-87b9-f789ab0a4ecc.png)
![leather-water-flask (3-4)](https://user-images.githubusercontent.com/59576000/72207504-cb10ce80-3491-11ea-99e3-2aa138abec63.png)
![leather-water-flask (broken)](https://user-images.githubusercontent.com/59576000/72207505-cb10ce80-3491-11ea-97c9-1e3891d83d07.png)
![leather-water-flask (empty)](https://user-images.githubusercontent.com/59576000/72207506-cba96500-3491-11ea-864d-9f2705cbacc7.png)
![leather-water-flask (Full)](https://user-images.githubusercontent.com/59576000/72207507-cba96500-3491-11ea-87c8-eb28cf74880b.png)

@Gaelmare Here are the new textures. I think the original leather flask should actually be 1/4 instead of 3/4 and I designed the rest accordingly. I also added in some broken flask textures for convenience. This should make everyone's drinking experience _immersive_. I am always more active on Discord so if you would like it, here is my discord: Coach#7087.

**Comment by Gaelmare** [comment]
I'm not how else to communicate this to all our users? Right in the
curseforge page for this add-on I say come to the #tng-addons channel in
the TFC discord for support.

I'll add you on discord.

**Comment by Coach-mdl** [comment]
[All Textures from Coach.zip](https://github.com/Gaelmare/WaterFlasks/files/4051589/All.Textures.from.Coach.zip)
All textures.

**Comment by Gaelmare** [comment]
Textures look great!
